# -*- coding: utf-8 -*-
"""M22CS007_task5.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16g-HIPjfssawFJplCt7XBmZyLvbAPzVk
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['glass.csv']))
df

columnnames=["Id_number","RI","Na","Mg","Al","Si",
            "K","Ca","Ba","Fe","window_glass"]
df= pd.read_csv("glass.csv", header=None, names=columnnames )

df.head()



newdf=df.replace({'window_glass' : { 7 : 0, 6 : 0, 5:0}})
newdf=df1.replace({'window_glass' : { 1 : 1, 2 : 1, 3:1}})
x=df.drop(['window_glass'],axis=1).values
y=newdf['window_glass'].values
newdf
y.shape[0]

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import plot_confusion_matrix

x_t,x_v,y_t,y_v=train_test_split(x,y,random_state=20)

reg=LogisticRegression()
reg.fit(x_t,y_t)

conf=plot_confusion_matrix(reg,x_v,y_v,cmap='Reds',values_format='.2g')

conf.confusion_matrix

